# Generated by Django 4.0.3 on 2022-03-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='parent',
            new_name='question',
        ),
    ]
