# Generated by Django 4.0.3 on 2022-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_like',
            field=models.BooleanField(null=True),
        ),
    ]
