# Generated by Django 4.0.3 on 2022-03-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        ('reviews', '0003_reviews_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='is_like',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.question'),
        ),
    ]
